In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pandas.plotting import scatter_matrix
from sklearn.decomposition import PCA # PCA

In [2]:
# 데이터 불러오기
data = pd.read_csv("project_data.csv")

## 첫번째 분석 방법

### 1) 이상치 제거
### 2) 정규화
### 3) PCA
### 4) 로지스틱을 이용한 분류

In [3]:
data1 = data

In [4]:
# value - mean의 절대값이 5시그마 밖의 값이면 이상치라 가정하고 제거
for i in data1.iloc[:,1:30]:
    data1 = data1[~(abs(data1[i] - data1[i].mean()) > 5*data1[i].std())] 

In [5]:
# X, Y로 나누고 X값들을 정규화
X = data1.iloc[:,1:30]
Y = data1.iloc[:,30]
for i in X:
    X[i] = (X[i] - X[i].mean())/X[i].std()

In [6]:
# PCA
pca_num = PCA(n_components=29)
X_PCA_T = pca_num.fit_transform(X)
X_PCA = pca_num.fit(X)

X_PCA_sum = np.cumsum(np.round(X_PCA.explained_variance_ratio_, decimals=8)*100) 
X_PCA_sum_varc = np.array(np.transpose(X_PCA_sum[:,np.newaxis])) 

X_PCA_sum_varc

array([[ 7.623337, 14.352209, 20.633861, 26.349525, 31.617967, 36.534743,
        41.3223  , 45.939378, 50.463384, 54.809141, 59.039765, 63.003636,
        66.77815 , 70.394455, 73.951452, 77.480637, 80.995487, 84.416027,
        87.800113, 90.622305, 92.593778, 94.37697 , 95.80591 , 97.172102,
        98.294107, 99.189599, 99.956628, 99.997534, 99.999998]])

위 결과에서 17번까지의 특징을 이용하면 전체 데이터의 80%를 설명할 수 있다

In [7]:
pc_y = np.c_[X_PCA_T,Y]
# 데이터프레임으로 변경
Data = pd.DataFrame(pc_y)

X = Data.iloc[:,0:17]
Y = Data.iloc[:,29]

In [8]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

Log = LogisticRegression().fit(X_train, y_train)

Log_target_predict = Log.predict(X_test)

print(classification_report(y_test, Log_target_predict))

C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     74681
         1.0       0.00      0.00      0.00        23

   micro avg       1.00      1.00      1.00     74704
   macro avg       0.50      0.50      0.50     74704
weighted avg       1.00      1.00      1.00     74704



C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


위 결과를 봤을 때 어떤 데이터를 넣어도 Class = 0으로 예측을 한 것을 알 수 있다.

결과적으로 Class가 1인 데이터를 하나도 분류하지 못했다.

- 발견한 것 : 이상치 제거할 때 Class 값이 1인 데이터들이 대략 70%, Class가 0인 데이터는 50%가 사라진 것을 발견            

## 두번째 분석 방법

### 1) 정규화
### 2) PCA
### 3) 로지스틱을 이용한 분류

In [9]:
data2 = data

In [10]:
# X, Y로 나누고 X값들을 정규화
X = data2.iloc[:,1:30]
Y = data2.iloc[:,30]a
for i in X:
    X[i] = (X[i] - X[i].mean())/X[i].std()

In [11]:
# PCA
pca_num = PCA(n_components=29)
X_PCA_T = pca_num.fit_transform(X)
X_PCA = pca_num.fit(X)

X_PCA_sum = np.cumsum(np.round(X_PCA.explained_variance_ratio_, decimals=8)*100) 
X_PCA_sum_varc = np.array(np.transpose(X_PCA_sum[:,np.newaxis])) 

X_PCA_sum_varc

array([[  6.821957,  10.472614,  14.054332,  17.581883,  21.059338,
         24.534958,  28.005411,  31.473655,  34.935393,  38.39431 ,
         41.84903 ,  45.301213,  48.746796,  52.188403,  55.628551,
         59.061438,  62.492848,  65.919956,  69.344699,  72.766799,
         76.186152,  79.598404,  83.005469,  86.410194,  89.806455,
         93.191683,  96.556926,  99.865013, 100.      ]])

위 결과에서 23번까지의 특징을 이용하면 전체 데이터의 80%를 설명할 수 있다

In [12]:
pc_y = np.c_[X_PCA_T,Y]
# 데이터프레임으로 변경
Data = pd.DataFrame(pc_y)

X = Data.iloc[:,0:23]
Y = Data.iloc[:,29]

In [13]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

Log = LogisticRegression().fit(X_train, y_train)

y_pred = Log.predict(X_test)

print(classification_report(y_test, y_pred))

C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     79602
         1.0       0.83      0.59      0.69       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.92      0.80      0.85     79746
weighted avg       1.00      1.00      1.00     79746



In [14]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[79585,    17],
       [   59,    85]], dtype=int64)

위 결과를 봤을 때 Class = 1인 데이터를 받았을때 1이라고 할 확률이 59%이므로 좋지도 나쁘지도 않은 결과이다

=> PCA가 의미 없다는 것을 확인

## 세번째 분석 방법

### 1) 정규화
### 2) 로지스틱을 이용한 분류

In [15]:
data3 = data

In [16]:
# X, Y로 나누고 X값들을 정규화
X = data3.iloc[:,1:30]
Y = data3.iloc[:,30]
for i in X:
    X[i] = (X[i] - X[i].mean())/X[i].std()

In [17]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

Log = LogisticRegression().fit(X_train, y_train)

y_pred = Log.predict(X_test)

print(classification_report(y_test, y_pred))

C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.83      0.59      0.69       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.92      0.80      0.85     79746
weighted avg       1.00      1.00      1.00     79746



In [18]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[79585,    17],
       [   59,    85]], dtype=int64)

위 결과를 봤을 때 Class = 1인 데이터를 받았을때 1이라고 할 확률이 59%이므로 PCA를 이용한 결과와 거의 동일하다고 볼 수 있다.

## 네번째 분석 방법

### 1) 정규화
### 2) 분산이 높은 특징 추출(OLS Regression Results)
### 3) 로지스틱을 이용한 분류

In [19]:
data4 = data

In [20]:
# X, Y로 나누고 X값들을 정규화
X = data4.iloc[:,1:30]
Y = data4.iloc[:,30]
for i in X:
    X[i] = (X[i] - X[i].mean())/X[i].std()

In [21]:
import statsmodels.api as sm
x2 = sm.add_constant(X)
model = sm.OLS(Y,x2)
result = model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                  Class   R-squared:                       0.511
Model:                            OLS   Adj. R-squared:                  0.511
Method:                 Least Squares   F-statistic:                     7193.
Date:                Wed, 12 Jun 2019   Prob (F-statistic):               0.00
Time:                        15:57:08   Log-Likelihood:             4.1946e+05
No. Observations:              199364   AIC:                        -8.389e+05
Df Residuals:                  199334   BIC:                        -8.385e+05
Df Model:                          29                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0018   6.61e-05     27.013      0.0

위 결과에서 각 특징별 t값이 있는데 t값이 높다는 것은 그 특징이 유의미한 특징임을 의미한다.

먼저 각 특징별 t값의 절댓값이 50이 넘는 특징을 선택해 분류해 보려고 한다.

V3,V4,V7,V9,V10,V11,V12,V14,V16,V17,V18 열한개의 특징을 사용

In [22]:
X = data.iloc[:,[3,4,7,9,10,11,12,14,16,17,18]]
Y = data.iloc[:,30]

In [23]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

Log = LogisticRegression().fit(X_train, y_train)

y_pred = Log.predict(X_test)

print(classification_report(y_test, y_pred))

C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.84      0.61      0.71       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.92      0.81      0.85     79746
weighted avg       1.00      1.00      1.00     79746



In [24]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[79585,    17],
       [   56,    88]], dtype=int64)

여전히 Class = 1인 데이터를 받았을때 1이라고 할 확률이 61%이므로 크게 달라진 점은 없다.

## 다섯번째 분석 방법

### 1) 정규화
### 2) 분산이 높은 특징 추출(컴퓨터)
### 3) 로지스틱을 이용한 분류

In [25]:
data5 = data

In [26]:
# X, Y로 나누고 X값들을 정규화
X = data5.iloc[:,1:30]
Y = data5.iloc[:,30]
for i in X:
    X[i] = (X[i] - X[i].mean())/X[i].std()

In [27]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LinearRegression

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.5,random_state=1)
Log = LinearRegression().fit(X_train, y_train)

In [28]:
from sklearn.svm import SVR 
from sklearn.feature_selection import RFE 
from sklearn import datasets
selector = RFE(Log, 10).fit(X_train, y_train) #  전체 특징 중 중요한 10개의 특징을 정해줌
print(selector.support_) 
print(selector.ranking_)

[False False  True  True False False  True False False  True  True  True
 False  True False  True  True  True False False False False False False
 False False False False False]
[ 3  4  1  1  5  7  1 10  2  1  1  1 13  1 15  1  1  1  9 20  8 19 18 12
 17 16 11 14  6]


In [29]:
X = data.iloc[:,[3,4,7,10,11,12,14,16,17,18]]
Y = data.iloc[:,30]

In [30]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

Log = LogisticRegression().fit(X_train, y_train)

y_pred = Log.predict(X_test)

print(classification_report(y_test, y_pred))

C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.84      0.61      0.71       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.92      0.81      0.85     79746
weighted avg       1.00      1.00      1.00     79746



In [31]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[79585,    17],
       [   56,    88]], dtype=int64)

Class = 1인 데이터를 받았을때 1이라고 할 확률이 61%이므로 분석 결과 위와 동일하다.

## 여섯번째 분석 방법

### 1) 정규화
### 2) 직관적으로 분석

In [32]:
X = data

In [33]:
y_test = X.iloc[:,30]
y_pred = np.zeros((199364,))

In [34]:
A = X[X.iloc[:,30]==1]
B = X[X.iloc[:,30]==0]

In [35]:
A_mean = pd.DataFrame(A.mean())
A_std = pd.DataFrame(A.std())
B_mean = pd.DataFrame(B.mean())
B_std = pd.DataFrame(B.std())

In [36]:
pd.concat([A_mean,B_mean,A_std,B_std],axis =1 )

0             0             0             0
Time    78200.033708  94806.329851  46673.000303  47449.330060
V1         -4.632999      0.004912      6.631320      1.933816
V2          3.489100     -0.005241      4.246547      1.645631
V3         -6.850015      0.012663      6.982269      1.461915
V4          4.518063     -0.004937      2.805339      1.401313
V5         -3.087808      0.006131      5.314190      1.362864
V6         -1.383572      0.002310      1.817774      1.333186
V7         -5.422761      0.011606      6.985212      1.191909
V8          0.625195     -0.002245      6.235322      1.167796
V9         -2.529519      0.005249      2.450965      1.090603
V10        -5.646788      0.008623      4.861166      1.048837
V11         3.805626     -0.005415      2.769000      1.003338
V12        -6.296140      0.009571      4.758574      0.947468
V13        -0.100056     -0.003023      1.091773      0.995316
V14        -6.928370      0.011478      4.314998      0.898550
V15        -0.139255     -0.000036      1.059640      0.916471
V16        -4.145130      0.007950      3.892930      0.844599
V17        -6.669539      0.012271      7.035489      0.751671
V18        -2.265586      0.004175      2.914884      0.824858
V19         0.638346     -0.001477      1.521087      0.811743
V20         0.381991     -0.000151      1.259876      0.779093
V21         0.755212     -0.000944      3.578670      0.722116
V22        -0.021713     -0.000053      1.392154      0.724174
V23        -0.087463      0.001891      1.691020      0.610299
V24        -0.114113     -0.000082      0.525555      0.605397
V25         0.064575      0.001037      0.823966      0.521177
V26         0.041963     -0.000157      0.481518      0.483148
V27         0.166356      0.000452      1.371467      0.401924
V28         0.091916     -0.000230      0.539651      0.330372
Amount    136.749551     88.367752    286.732453    253.150968
Class       1.000000      0.000000      0.000000      0.000000

현재 문제는 Class 값이 1과 0을 구분하는 것이기 때문에 Class = 1과 0을 그룹화 한 뒤 각 특징별 평균,분산의 차이를 확인했는데 V1,V2,V3,V5,V7,V8,V10,V12,V14,V16,V17의 분산이 차이가 있음과 동시에 평균의 차이도 나는 것을 발견했습니다.

In [37]:
X = data.iloc[:,[1,2,3,5,7,8,10,12,14,16,17]]
Y = data.iloc[:,30]

In [38]:
from sklearn.model_selection  import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

Log = LogisticRegression().fit(X_train, y_train)

y_pred = Log.predict(X_test)

print(classification_report(y_test, y_pred))

C:\Users\sunni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.90      0.56      0.69       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.95      0.78      0.85     79746
weighted avg       1.00      1.00      1.00     79746



위의 값을 확인했을 때 logistic을 이용하면 한계가 있다는 것을 알 수 있다.

## 일곱번째 분석 방법
### 1) 중요한 특징 추출(세가지 방법)
### 2) KNN



네번째 분석 할 때 OLS Regression Results에서 t값을 기준으로 특징을 추출

위와 같이 50이 넘는 특징을 사용

이렇게 V3,V4,V7,V9,V10,V11,V12,V14,V16,V17,V18 열한개의 특징만 사용해 KNN에 모델링을 함

In [39]:
from sklearn.model_selection  import train_test_split
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import f1_score

In [40]:
X = data.iloc[:,[3,4,7,9,10,11,12,14,16,17,18]]
Y = data.iloc[:,30]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4, random_state=1)

for i in range(3,50,20):
    reg = KNeighborsRegressor(n_neighbors=i)
    
    reg.fit(X_train, y_train)

    y_pred = reg.predict(X_test)

    y_pred_classes = np.zeros_like(y_pred)
    y_pred_classes[y_pred > 0] = 1 # 이웃중 하나라도 1이 있으면 1로 분류
    
    print("현재 K의 개수")
    print(i)
    print(f1_score(y_test, y_pred_classes))
    print(classification_report(y_test, y_pred_classes))
    print()
    print()
    print()
    print()
    
    y_pred_sort = np.sort(y_pred)[::-1] # 예측한 값을 내림차순으로 정렬

    a = np.array(pd.DataFrame(y_pred_sort).rank(ascending = False, method = 'min')[0]) # 내림차순한 확률값에 순위매기기(중복 값은 작은 값으로)

    rank = np.vstack([y_pred_sort,a]) # 확률값과 순위값 합치기

    pd.DataFrame(rank)

    cnt = 0
    sum_rank = 0
    for i in y_test:
        if i==1: # 클래스가 1인 데이터의 확률값과 순위를 확인해 sum_rank에 더해줌
            sum_rank += np.where(rank[0] == y_pred[cnt])[0][0]
        cnt += 1

    print(sum_rank / sum(y_test)) # 전체 순위의 평균값 출력
    
    print()
    print()
    print()

현재 K의 개수
3
0.7155425219941349
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.62      0.85      0.72       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.81      0.92      0.86     79746
weighted avg       1.00      1.00      1.00     79746





47.97222222222222



현재 K의 개수
23
0.3668639053254438
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     79602
           1       0.23      0.86      0.37       144

   micro avg       0.99      0.99      0.99     79746
   macro avg       0.62      0.93      0.68     79746
weighted avg       1.00      0.99      1.00     79746





129.31944444444446



현재 K의 개수
43
0.2727272727272727
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     79602
           1       0.16      0.88      0.27       144

   micro avg       0.99      0.99      

다섯번째 분석 할 때 selector.ranking_에서 특징 10개씩 묶었을 때 가장 R-Square값이 높은 10개의 특징을 추출

이렇게 10개의 특징만 사용해 KNN에 모델링을 함

In [41]:
X = data.iloc[:,[3,4,7,10,11,12,14,16,17,18]]
Y = data.iloc[:,30]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4, random_state=1)

for i in range(3,50,20):
    reg = KNeighborsRegressor(n_neighbors=i)
    reg.fit(X_train, y_train)

    y_pred = reg.predict(X_test)

    y_pred_classes = np.zeros_like(y_pred)
    y_pred_classes[y_pred > 0] = 1 
    
    print("현재 K의 개수")
    print(i)
    print(f1_score(y_test, y_pred_classes))
    print(classification_report(y_test, y_pred_classes))
    print()
    
    
    print()
    print()
    print()
    
    y_pred_sort = np.sort(y_pred)[::-1] # 예측한 값을 내림차순으로 정렬

    a = np.array(pd.DataFrame(y_pred_sort).rank(ascending = False, method = 'min')[0]) # 내림차순한 확률값에 순위매기기(중복 값은 작은 값으로)

    rank = np.vstack([y_pred_sort,a]) # 확률값과 순위값 합치기

    pd.DataFrame(rank)

    cnt = 0
    sum_rank = 0
    for i in y_test:
        if i==1: # 클래스가 1인 데이터의 확률값과 순위를 확인해 sum_rank에 더해줌
            sum_rank += np.where(rank[0] == y_pred[cnt])[0][0]
        cnt += 1

    print(sum_rank / sum(y_test)) # 전체 순위의 평균값 출력
    
    print()
    print()
    print()

현재 K의 개수
3
0.7155425219941349
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.62      0.85      0.72       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.81      0.92      0.86     79746
weighted avg       1.00      1.00      1.00     79746





47.74305555555556



현재 K의 개수
23
0.362844702467344
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     79602
           1       0.23      0.87      0.36       144

   micro avg       0.99      0.99      0.99     79746
   macro avg       0.61      0.93      0.68     79746
weighted avg       1.00      0.99      1.00     79746





128.44444444444446



현재 K의 개수
43
0.2677824267782427
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     79602
           1       0.16      0.89      0.27       144

   micro avg       0.99      0.99      0

여섯번째 분석 할 때 직접 클래스별 특징의 평균과 분산을 비교해 가장 육안으로 차이가 나는 특징 11개를 추출
이렇게 V1,V2,V3,V5,V7,V8,V10,V12,V14,V16,V17 열한개의 특징만 사용해 KNN에 모델링을 함

In [42]:
X = data.iloc[:,[1,2,3,5,7,8,10,12,14,16,17]]
Y = data.iloc[:,30]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4, random_state=1)

for i in range(3,50,20):
    reg = KNeighborsRegressor(n_neighbors=i)
    reg.fit(X_train, y_train)

    y_pred = reg.predict(X_test)

    y_pred_classes = np.zeros_like(y_pred)
    y_pred_classes[y_pred > 0] = 1 
    
    print("현재 K의 개수")
    print(i)
    print(f1_score(y_test, y_pred_classes))
    print(classification_report(y_test, y_pred_classes))
    print()
    
    
    
    print()
    print()
    print()
    
    y_pred_sort = np.sort(y_pred)[::-1] # 예측한 값을 내림차순으로 정렬

    a = np.array(pd.DataFrame(y_pred_sort).rank(ascending = False, method = 'min')[0]) # 내림차순한 확률값에 순위매기기(중복 값은 작은 값으로)

    rank = np.vstack([y_pred_sort,a]) # 확률값과 순위값 합치기

    pd.DataFrame(rank)

    cnt = 0
    sum_rank = 0
    for i in y_test:
        if i==1: # 클래스가 1인 데이터의 확률값과 순위를 확인해 sum_rank에 더해줌
            sum_rank += np.where(rank[0] == y_pred[cnt])[0][0]
        cnt += 1

    print(sum_rank / sum(y_test)) # 전체 순위의 평균값 출력
    
    print()
    print()
    print()

현재 K의 개수
3
0.7407407407407408
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.67      0.83      0.74       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.83      0.92      0.87     79746
weighted avg       1.00      1.00      1.00     79746





48.708333333333336



현재 K의 개수
23
0.39360000000000006
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.26      0.85      0.39       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.63      0.92      0.70     79746
weighted avg       1.00      1.00      1.00     79746





125.11805555555556



현재 K의 개수
43
0.27114967462039047
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     79602
           1       0.16      0.87      0.27       144

   micro avg       0.99      0.99   

세개의 KNN분석을 봤는데 결과적으로 랭킹의 평균이 가장 낮게 하기 위해서는 컴퓨터가 중요하다고 생각하는 10개의 특징으로 모델링을 했을 때 가장 낮게 나온것을 알 수 있다.

위의 모델에서 X의 값을 정규화 한 뒤 성능 확인

In [44]:
# X, Y로 나누고 X값들을 정규화
X = data.iloc[:,1:30]
Y = data.iloc[:,30]
for i in X:
    X[i] = (X[i] - X[i].mean())/X[i].std()

X = X.iloc[:,[2,3,6,8,9,10,11,13,15,16,17]] # V3,V4,V7,V10,V11,V12,V14,V16,V17,V18 열개의 특징사용
Y = data.iloc[:,30]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4, random_state=1)

reg = KNeighborsRegressor(n_neighbors=3) # 이웃의 수를 3개 확인
    
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)

y_pred_classes = np.zeros_like(y_pred)
y_pred_classes[y_pred > 0] = 1 # 이웃중 하나라도 1이 있으면 1로 분류
    

print(classification_report(y_test, y_pred_classes))
print()
print()
    
y_pred_sort = np.sort(y_pred)[::-1] # 예측한 값을 내림차순으로 정렬

a = np.array(pd.DataFrame(y_pred_sort).rank(ascending = False, method = 'min')[0]) # 내림차순한 확률값에 순위매기기(중복 값은 작은 값으로)

rank = np.vstack([y_pred_sort,a]) # 확률값과 순위값 합치기

pd.DataFrame(rank)

cnt = 0
sum_rank = 0
for i in y_test:
    if i==1: # 클래스가 1인 데이터의 확률값과 순위를 확인해 sum_rank에 더해줌
        sum_rank += np.where(rank[0] == y_pred[cnt])[0][0]
    cnt += 1

print("1인 데이터들의 평균 순위 ")
print(sum_rank / sum(y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.60      0.85      0.70       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.80      0.92      0.85     79746
weighted avg       1.00      1.00      1.00     79746



1인 데이터들의 평균 순위 
50.09027777777778


정규화를 했을 떄 랭킹의 평균 순위가 높아지는것을 볼 수 있다.

# - 최종 모델은 다음과 같다

## 각 랭킹값의 평균이 최소가 되는 분류모델은 컴퓨터가 중요하다고 생각하는 10개의 특징(V3,V4,V7,V10,V11,V12,V14,V16,V17,V18)으로 KNN 모델링 했을 때 가장 최소가 나온다.

In [50]:
X = data.iloc[:,[3,4,7,10,11,12,14,16,17,18]]
Y = data.iloc[:,30]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4, random_state=1)

reg = KNeighborsRegressor(n_neighbors=3) # 이웃의 수를 3부터 293까지 확인
    
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)

y_pred_classes = np.zeros_like(y_pred)
y_pred_classes[y_pred > 0] = 1 # 이웃중 하나라도 1이 있으면 1로 분류
    
print("현재 K의 개수")
print(i)
print(f1_score(y_test, y_pred_classes))
print(classification_report(y_test, y_pred_classes))
print()
print()
print()
print()
    
y_pred_sort = np.sort(y_pred)[::-1] # 예측한 값을 내림차순으로 정렬

a = np.array(pd.DataFrame(y_pred_sort).rank(ascending = False, method = 'min')[0]) # 내림차순한 확률값에 순위매기기(중복 값은 작은 값으로)

rank = np.vstack([y_pred_sort,a]) # 확률값과 순위값 합치기

pd.DataFrame(rank)

cnt = 0
sum_rank = 0
for i in y_test:
    if i==1: # 클래스가 1인 데이터의 확률값과 순위를 확인해 sum_rank에 더해줌
        sum_rank += np.where(rank[0] == y_pred[cnt])[0][0]
        print(np.where(rank[0] == y_pred[cnt])[0][0])
    cnt += 1

print(sum_rank / sum(y_test)) # 전체 순위의 평균값 출력

현재 K의 개수
1
0.7155425219941349
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79602
           1       0.62      0.85      0.72       144

   micro avg       1.00      1.00      1.00     79746
   macro avg       0.81      0.92      0.86     79746
weighted avg       1.00      1.00      1.00     79746





0
0
0
0
99
0
0
0
0
99
0
0
197
0
197
0
0
0
0
0
0
99
0
197
99
0
0
0
0
99
0
0
197
0
0
0
0
0
0
0
0
0
197
0
99
0
0
99
0
197
197
197
99
0
0
0
99
0
99
0
0
132
0
99
0
197
0
99
197
0
0
0
0
0
0
197
0
0
0
0
132
0
0
0
0
0
132
197
197
99
197
99
0
0
0
0
0
197
197
99
197
132
197
99
0
0
0
99
0
0
0
0
0
0
0
0
0
0
99
197
0
197
197
0
0
0
0
0
132
197
99
0
0
0
0
0
0
0
0
0
0
0
0
0
47.74305555555556


In [47]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred_classes)
cnf_matrix

array([[79527,    75],
       [   22,   122]], dtype=int64)