In [2]:
import pandas as pd
import numpy as np
import os.path
import csv
import operator

In [3]:
# 영화 300개 자료 저장
# User 수는 1000명
data = {}
movie_id = 0
user_name = 0
rating = 0
user_list = []


with open('combined_data_1.txt', 'r') as f:
    for line in f:
        if(line.find(":") != -1):
            continue
        line_split = line.split(',')
        user_name = int(line_split[0])
        if user_name in user_list:
            continue
        else:
            user_list.append(user_name)
        if len(user_list) > 1000:
            break

with open('combined_data_1.txt', 'r') as f:
    for line in f:
        if(line.find(":") != -1):
            movie_id = int(line.replace(":","")) - 1
            if(movie_id >= 300): break
            data[movie_id] = {}
        else:
            line_split = line.split(',')
            user_name = int(line_split[0])
            rating = int(line_split[1])
            if user_name in user_list:
                data[movie_id][user_name] = rating

In [4]:
### 영화, 사용자, rating 정보를 2차원 배열에 저장
### 1000 x 300 영화, 사용자 2차원 배열

matrix = [[np.nan for col in range(300)] for row in range(1000)]

for i in range(1000):
    for j in range(300):
        if(user_list[i] in data[j]):
            matrix[i][j] = data[j][user_list[i]]
        
matrix = np.array(matrix)

matrix[:5]

array([[ 3., nan, nan, ..., nan,  3., nan],
       [ 5., nan, nan, ..., nan, nan, nan],
       [ 4., nan, nan, ..., nan, nan, nan],
       [ 4., nan, nan, ..., nan,  4., nan],
       [ 3., nan, nan, ..., nan, nan, nan]])

In [5]:
# module 불러오기
import module

In [6]:
module.EUC(matrix)

array([[ 0.        , 18.22086716, 21.14237451, ..., 19.23538406,
        19.49358869, 18.24828759],
       [18.22086716,  0.        , 12.20655562, ..., 10.86278049,
         9.59166305, 11.26942767],
       [21.14237451, 12.20655562,  0.        , ..., 16.03121954,
        15.19868415, 16.30950643],
       ...,
       [19.23538406, 10.86278049, 16.03121954, ...,  0.        ,
        10.95445115, 13.07669683],
       [19.49358869,  9.59166305, 15.19868415, ..., 10.95445115,
         0.        , 11.78982612],
       [18.24828759, 11.26942767, 16.30950643, ..., 13.07669683,
        11.78982612,  0.        ]])

In [7]:
module.COS(matrix)

COS calculation start!
COS calculation end!


array([[1.        , 1.        , 0.92609236, ..., 0.96225045, 0.89442719,
        0.83508588],
       [1.        , 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.92609236, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.96225045, 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.89442719, 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.83508588, 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ]])

In [8]:
module.PCC(matrix)

PCC calculation start!
PCC calculation end!


array([[-1.        ,  0.        , -0.95921363, ...,  0.24485105,
         0.81373347, -0.13612723],
       [ 0.        , -1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.95921363,  0.        , -1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.24485105,  0.        ,  0.        , ..., -1.        ,
         1.        , -1.        ],
       [ 0.81373347,  0.        ,  0.        , ...,  1.        ,
        -1.        , -1.        ],
       [-0.13612723,  0.        ,  0.        , ..., -1.        ,
        -1.        , -1.        ]])

In [9]:
module.basic_CF(matrix, 'PCC', 3)

PCC calculation start!
PCC calculation end!


array([[0.        , 2.33333333, 1.        , ..., 0.        , 0.66666667,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [2.        , 0.        , 1.66666667, ..., 0.        , 1.33333333,
        0.        ],
       ...,
       [0.66666667, 0.        , 2.66666667, ..., 0.66666667, 2.66666667,
        0.        ],
       [0.        , 0.        , 4.66666667, ..., 0.        , 1.        ,
        0.        ],
       [3.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ]])

In [10]:
module.basic_CF(matrix, 'COS', 3)

COS calculation start!
COS calculation end!


array([[1.        , 0.        , 2.33333333, ..., 0.        , 1.        ,
        0.        ],
       [4.        , 0.        , 0.        , ..., 0.        , 2.        ,
        0.        ],
       [4.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.33333333, 0.        , 2.66666667, ..., 0.        , 2.        ,
        0.        ],
       [0.        , 0.        , 3.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.66666667, ..., 0.        , 0.        ,
        0.        ]])

In [11]:
module.basic_mean(matrix, 'PCC', 3)

PCC calculation start!
PCC calculation end!


array([[-0.30645161,  2.02688172,  0.69354839, ..., -0.30645161,
         0.36021505, -0.30645161],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 2.74603175,  0.74603175,  2.41269841, ...,  0.74603175,
         2.07936508,  0.74603175],
       ...,
       [ 0.83549784,  0.16883117,  2.83549784, ...,  0.83549784,
         2.83549784,  0.16883117],
       [-0.20277778, -0.20277778,  4.46388889, ..., -0.20277778,
         0.79722222, -0.20277778],
       [ 2.68333333, -0.31666667,  0.68333333, ..., -0.31666667,
        -0.31666667, -0.31666667]])

In [12]:
module.basic_mean(matrix, 'COS', 3)

COS calculation start!
COS calculation end!


array([[ 0.78243728, -0.21756272,  2.11577061, ..., -0.21756272,
         0.78243728, -0.21756272],
       [ 5.35770609,  1.35770609,  1.35770609, ...,  1.35770609,
         3.35770609,  1.35770609],
       [ 4.18518519, -0.14814815, -0.14814815, ..., -0.14814815,
        -0.14814815, -0.14814815],
       ...,
       [ 1.15584416, -0.17748918,  2.48917749, ..., -0.17748918,
         1.82251082, -0.17748918],
       [ 0.48333333,  0.48333333,  3.81666667, ...,  0.48333333,
         0.48333333,  0.48333333],
       [-0.08333333, -0.08333333,  3.58333333, ..., -0.08333333,
        -0.08333333, -0.08333333]])

In [13]:
module.basic_zscore(matrix, 'PCC', 3)

PCC calculation start!
PCC calculation end!


array([[-1.96330077,  1.92915628, -0.8633055 , ..., -1.96330077,
        -0.80380395, -1.96330077],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 2.85768075,  0.48252984,  1.96401133, ...,  0.48252984,
         1.79428947,  0.48252984],
       ...,
       [-0.24695491, -0.7950151 ,  3.05648103, ..., -0.24695491,
         3.05648103, -0.7950151 ],
       [-1.20722462, -1.20722462,  4.62154586, ..., -1.20722462,
        -0.09386082, -1.20722462],
       [ 0.93153485, -4.48709194, -1.52905204, ..., -4.48709194,
        -4.48709194, -4.48709194]])

In [14]:
module.basic_zscore(matrix, 'COS', 3)

COS calculation start!
COS calculation end!


array([[-1.21864809, -2.08827071,  2.3431725 , ..., -2.08827071,
         0.11171983, -2.08827071],
       [ 5.        ,  5.        ,  5.        , ...,  5.        ,
         5.        ,  5.        ],
       [ 4.19561403,  3.47719282,  3.47719282, ...,  3.47719282,
         3.47719282,  3.47719282],
       ...,
       [ 1.32129454,  0.24632684,  2.76448963, ...,  0.24632684,
         3.30197348,  0.24632684],
       [-0.11749265, -0.11749265,  4.06759214, ..., -0.11749265,
        -0.11749265, -0.11749265],
       [ 1.12613698,  1.12613698,  3.90990215, ...,  1.12613698,
         1.12613698,  1.12613698]])

In [15]:
module.basic_baseline(matrix, 'PCC', 3)

PCC calculation start!
PCC calculation end!


array([[0.00000000e+00, 2.33333333e+00, 1.00000000e+00, ...,
        0.00000000e+00, 6.66666667e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 1.66666667e+00, ...,
        0.00000000e+00, 1.33333333e+00, 0.00000000e+00],
       ...,
       [6.66666667e-01, 4.44089210e-16, 2.66666667e+00, ...,
        6.66666667e-01, 2.66666667e+00, 4.44089210e-16],
       [0.00000000e+00, 0.00000000e+00, 4.66666667e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [16]:
module.basic_baseline(matrix, 'COS', 3)

COS calculation start!
COS calculation end!


array([[ 1.00000000e+00,  0.00000000e+00,  2.33333333e+00, ...,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 4.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  2.00000000e+00,  0.00000000e+00],
       [ 4.33333333e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.33333333e+00,  0.00000000e+00,  2.66666667e+00, ...,
         0.00000000e+00,  2.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  3.33333333e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -4.44089210e-16,  3.66666667e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])